sudo: false
dist: xenial
language: generic
jdk:
 - oraclejdk8
node_js:
  - "10.16.0"
before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
services:
 - docker
 - xvfb
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.cache/yarn
env:
  global:
  - DISPLAY=:99.0
  - MAVEN_OPTS="-Xmx4g"
  - TERM=dumb
  - TARGET=Latest.target
before_install:
- chmod +x $TRAVIS_BUILD_DIR/extensions/vscode/gradlew
jobs:
  include:
    - stage: Build YAKINDU Solidity IDE and language server
      script: 
      - cd releng/com.yakindu.solidity.releng
      - mvn clean verify -P$TARGET,tests
      - cd ../com.yakindu.solidity.repository/target
      - zip -r repository.zip repository
      #- cd $TRAVIS_BUILD_DIR/extensions/vscode
      #- ./gradlew vscodeExtension
      - cd $TRAVIS_BUILD_DIR
      - cp -r extensions/theia/ide extensions/theia/docker/theia_app/ide
      - cp -r plugins/com.yakindu.solidity.ide/target/languageserver extensions/theia/docker/theia_app/ide/xtext-dsl-extension/lsp
      - cd extensions/theia/docker/theia_app/ide
      - yarn install --production
      - cd $TRAVIS_BUILD_DIR
      - docker build extensions/theia/docker/theia_app/. -t yakindu/solidity-ide
deploy:
  skip_cleanup: true
  on:
    all_branches: true
  github_token: $GITHUB_TOKEN
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push yakindu/solidity-ide
