sudo: false
language: java
jdk: 
 - oraclejdk8
before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
services:
  - docker
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - DISPLAY=:99.0
  - MAVEN_OPTS="-Xmx4g"
  - TERM=dumb
  - TARGET=Latest.target
before_install:
- sh -e /etc/init.d/xvfb start - sleep 10
- chmod +x $TRAVIS_BUILD_DIR/extensions/vscode/gradlew
jobs:
  include:
    - stage: compile and test
      script: 
      - cd releng/com.yakindu.solidity.releng
      - mvn clean verify -P$TARGET,tests
      - cd ../com.yakindu.solidity.repository/target
      - zip -r repository.zip repository
    - stage: package
      script: 
      - cd $TRAVIS_BUILD_DIR/extensions/vscode && pwd
      - ./gradlew vscodeExtension
      script: 
      - cd $TRAVIS_BUILD_DIR
      - docker build extensions/theia/docker/theia_app/.
    - stage: deploy
      script: 
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-image
